version: "3.8"

services:
  app:
    image: ubuntu:22.04
    container_name: rag_fastapi_app

    volumes:
      - ./volume:/app/volume
      - ./code:/app/code
      - ./data:/app/data
    
    working_dir: /app/code
    
    ports:
      - "8000:8000"

    command: > 
      bash -c "
        apt-get update &&
        apt-get install -y python3.11 python3-pip &&
        pip install --upgrade pip &&
        pip install --no-cache-dir -r /app/code/requirements.txt
      "
    
    tty: true
